name: Test documentation

on:
  pull_request:
  push:
  schedule:
    - cron: "0 2 * * *" # run at 2 AM UTC

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 12
      matrix:
        python-version: [3.8]
        os: [ubuntu-latest]

    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.10.0
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: anaconda-client-env
      - name: Add conda to system path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt install pandoc
          pip install gdsfactory[dev] triangle
          make install
          make meep
      - name: Test documentation
        run: |
          cd docs
          make html
