---
name: Code test coverage
on:
  pull_request:
  push:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.9.1
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -e .
      - name: Test with pytest
        run: |
          pip install pytest
          pip install pytest-cov
          pytest --cov=ubcpdk --cov-report=xml
          pytest --cov=ubcpdk --cov-report=xml --cov-config=.coveragerc ubcpdk
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
